### ISSUE TITLE
Omitting the `path` property in the `sign` method's first argument should use a default value instead

### ISSUE THREAD

**Issue by oleiade** [grafana/k6-jslib-aws#48]
As [reported by a user ](https://github.com/grafana/k6-jslib-aws/issues/36#issuecomment-1580646640), when one omits to set the `path` property of the `sign` method first argument, it leads to an error:

```
ERRO[0000] TypeError: Cannot read property 'split' of undefined or null
        at value (webpack://k6-jslib-aws/./src/internal/signature.ts:404:37(12))
        at value (webpack://k6-jslib-aws/./src/internal/signature.ts:300:40(32))
        at value (webpack://k6-jslib-aws/./src/internal/signature.ts:146:40(213))
        at file:///.../k6-script.js:207:2(53)  executor=per-vu-iterations scenario=default source=stacktrace
```

We should probably make this property optional and use a default value instead, as it's quite common for requests to not need to override the path.

**Comment by oleiade** [comment]
I believe this is fixed.
